### ISSUE TITLE
issue with php7.1

### ISSUE THREAD

**Issue by bouroo** [ZzAntares/ProxmoxVE#15]
When use with php7.1 this error appear

> Fatal error: Cannot use lexical variable $eventName as a parameter name in /www/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 49

Will upgrade guzzlehttp/guzzle to latest statble fix this issue?

**Comment by ZzAntares** [comment]
Hi, could you try using the branch guzzle6? To see if that works?

**Comment by bouroo** [comment]
After used guzzle6 branch error message change to

> Call to undefined function GuzzleHttp\Promise\promise_for()
vendor/guzzlehttp/guzzle/src/Client.php:275

**Comment by ZzAntares** [comment]
It seems so, I could do some testing tomorrow, but by the look of the error yes it's a guzzle thing, I actually never used guzzle on php7 so I can't tell for sure, I'll do some tests, stay tuned 😃

**Comment by ZzAntares** [comment]
Well, as you found out using the stable release with php7 would not work because guzzle4. Using the `guzzle6` branch also does not work because it seems to be a problem in how the `PVEAuthProxmox` cookie is set and I need to fix that but I couldn't see any of the errors you described.

In the meantime you could try using the `v2.1.1` release which doesn't use guzzle but relies on pure curl, however `php7` compatibility isn't assured, I'll add a note on the readme about that to avoid missconceptions. If `v2.1.1` does not work for you then I'm afraid this package will be useless to you and you could try [other alternatives](https://pve.proxmox.com/wiki/Proxmox_VE_API#Clients).

I'll keep this open to remind me to officially add support to `php7`.

**Comment by ZzAntares** [comment]
Ok, I did an update to fix the issue with the cookie for the `guzzle6` branch, please try again be sure to refer to it in the `composer.json` as:

``` json
"require": {
    "zzantares/proxmoxve": "dev-guzzle6"
}
```

This is working fine on `PHP 7.1.0`:

``` php
<?php

require_once 'vendor/autoload.php';

use ProxmoxVE\Proxmox;

$credentials = [
    'hostname' => 'theserver',
    'username' => 'theuser',
    'password' => 'thepasswd',
];

$proxmox = new Proxmox($credentials);

$allNodes = $proxmox->get('/nodes');

var_dump($allNodes);
```

**Comment by bouroo** [comment]
Now after change to guzzle6 branch with PHP Version 7.1.0-5+deb.sury.org~xenial+1
My issues has gone.
Thx so much for your fix. ^_^

**Comment by bouroo** [comment]
Another error appear when POST

> "file":"/srv/cloud-mnt/vendor/guzzlehttp/guzzle/src/Client.php","line":402,"message":"Passing in the \"body\" request option as an array to send a POST request has been deprecated. Please use the \"form_params\" request option to send a application/x-www-form-urlencoded request, or a the \"multipart\" request option to send a multipart/form-data request."

I found that change 'body' to 'form_params' inside function requestResource will fix this.

**Comment by ZzAntares** [comment]
Hi, sorry the delay, hopefully #16 fixes this.

**Comment by harmen1994** [comment]
You're a genius, thanks!
