### ISSUE TITLE
Response type: object

### ISSUE THREAD

**Issue by poxin13** [ZzAntares/ProxmoxVE#19]
Cheers for the library, working great in laravel using the guzzle6 branch. I saw you had a placeholder for an object return type. Any plans to still add that in?

**Comment by ZzAntares** [comment]
Hello, I'm sorry but I don't have plans near in the future to further develop this library, perhaps some day I'll be bored and do just that, but I've moved on onto other things now. However writing an object layer shouldn't be difficult and perhaps the best approach is to do that in another package which has this package as a base dependency. 

I'm curious, how well does the `guzzle6 ` branch worked for you? Did you have any issue with it? I've been delaying the merge on to master due to "may be" being an unstable branch.

**Comment by poxin13** [comment]
No issues at all here, haven't ran into any errors. In my project I created a Laravel service provider and facade wrapping your package and that's also working great.

`Proxmox::get('/nodes')['data']`

If I feel up to writing the object layer I'll do a PR. Nothing wrong with arrays I just prefer looking at arrows ;)
