### ISSUE TITLE
Detecting Http error

### ISSUE THREAD

**Issue by mdenadal** [zzantares/ProxmoxVE#34]
Hi,
first of all:  thank you very much for your code!

I have a problem detecting http related errors.
In example, trying something like this:
`print_r ($proxmox->set('/nodes/foo/qemu/200/config'. ['lock' => 'bar']));`

I correctly get an error like:
 
    Array
    (    
        [errors] => Array
            (
                [lock] => value 'bar' does not have a value in the enumeration 'migrate, backup, snapshot, rollback'
            )
        
             [data] =>
    )
The error in in response body so it's correctly parsed.

But if error is in response header, like this case:
`print_r ($proxmox->set('/nodes/foo/qemuZZ/200/config'. ['lock' => 'bar']));`
I get no error at all:

    Array
    (
        [data] =>
    )

Am I missing something?
Regards,
Massimo

**Comment by ZzAntares** [comment]
Mmm if Proxmox doesn't send an error message I believe is not up to this library to give one for the user, but what do you mean by "_the error is in the response header_"? what's the header name?

I'll look into it, however I no longer have access to any testing Proxmox server, can you please perform the same request using `curl` or [`httpie`](https://httpie.org/) to the server to see how the bare response looks like? You can find info about how to send a request [here](https://pve.proxmox.com/wiki/Proxmox_VE_API).

Also let me say, I've hesitant to merge #33 but it may fix your problem since catches any 4xx error, you can try that and see if it works.
