### ISSUE TITLE
Timeout with GuzzleHttp

### ISSUE THREAD

**Issue by Ch4rlus** [ZzAntares/ProxmoxVE#37]
There's currently no timeout in the GuzzleHttp calls in this wrapper. That's not a big deal, but by default, GuzzleHttp waits indefinitely (or until your PHP gets killed).

We could probably consider adding an optional $timeout variable on the API calls, and pass it to the http calls ?

**Comment by ZzAntares** [comment]
Hello, thanks for reaching out!, sadly, I'm no longer focused in continue the development of this wrapper, I no longer do PHP and I no longer work with ProxmoxVE, but I consider the wrapper pretty stable, of course there will always be something missing but if I may be honest, I will not add it. I've updated the readme to make that clear.

I like your suggestion overall and invite you to submit a PR to add support for it but beware I will not merge if the code isn't properly tested, there's an open PR that touches on timeouts but is missing tests, perhaps you could finish it.

Otherwise you're free to fork, or even look at the existent forks that have been made, I believe some have various additions but I can't vouch for them.

If you're interested in working on this we can keep this issue open, otherwise it will be closed as will-not-fix. Thanks, and sorry! 😞

**Comment by Ch4rlus** [comment]
Hey ! Thanks for replying, and making it clear in the readme :)

I’ve already added some dirty hardcoded timeout in my code to fix the issue, therefore I will probably not take the time to submit a proper PR to this issue.

The wrapper is indeed pretty stable, and I’m currently using it across hundreds of proxmox servers without any other issue. Thanks for all the work & time you put in this project !

You can close the issue :)
